version: '3'

services: 
    web:
        image: odoo:14.0
        container_name: odoo_14
        depends_on: 
            - db
        ports: 
            - 9000:8069
        volumes: 
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
            - ./enterprise:/mnt/enterprise
        environment: 
            - HOST=db
            - USER=odoo14
            - PASSWORD=odoo14
        command: odoo -u all -i sale_management,stock,purchase,contacts -d odoo --dev all
    db:
        image: postgres:10
        container_name: postgres_10
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=odoo14
            - POSTGRES_USER=odoo14
            - POSTGRES_DB=postgres